<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Сайты</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
            {% for url in urls %}
                <tr>
                    <td>{{ url.id }}</td>
                    <td>
                        <a href="{{ url_for('url', { 'id': url.id }) }}">
                            {{ url.name }}
                        </a>
                    </td>
                    <td>{{ url.last_check_date }}</td>
                    <td>{{ url.status_code }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>