<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body class="d-flex flex-column min-vh-100">
<header class="flex-shrink-0">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('home') }}">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('home') }}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('urls') }}">Сайты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
</header>

{% for message in flashes.success %}
    <div class="alert alert-success">
        {{ message }}
    </div>
{% endfor %}

{% for message in flashes.error %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
{% endfor %}

<main class="flex-grow-1">
    <div class="container-lg mt-3 px-4 px-md-0">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>

                <form action="{{ url_for('addUrl') }}" method="post" class="d-flex flex-wrap flex-sm-nowrap">
                    <div class="flex-grow-1">
                        <input type="text" name="url[name]" value=""
                            class="form-control form-control-lg {% if errors.name %}is-invalid{% endif %}"
                            placeholder="https://www.example.com">
                        {% if errors.name %}
                            <p class="invalid-feedback">{{ errors.name|first }}</p>
                        {% endif %}
                    </div>

                    <div class="col-lg-3 flex-grow-1">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<footer class="footer mt-auto py-3 bg-light flex-shrink-0">
    <div class="container text-center">
        <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
    </div>
</footer>
</body>
</html>