<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body class="d-flex flex-column min-vh-100">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<?php if (!empty($flashes['success'])) : ?>
    <?php foreach ($flashes['success'] as $message) : ?>
        <div class="alert alert-success">
            <?= $message ?>
        </div>
    <?php endforeach ?>
<?php endif ?>

<?php if (!empty($flashes['error'])) : ?>
    <?php foreach ($flashes['error'] as $message) : ?>
        <div class="alert alert-danger">
            <?= $message ?>
        </div>
    <?php endforeach ?>
<?php endif ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3 px-4 px-md-0">
    <h1>Сайт: <?= htmlspecialchars($url['name'] ?? '') ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= htmlspecialchars($url['id'] ?? '') ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($url['name'] ?? '') ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($url['created_at'] ?? '') ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <h2 class="mt-5 mb-3">Проверки</h2>
        <form action="/urls/<?= htmlspecialchars($url['id']) ?>/checks" class="mt-3" method="post">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover mt-3" data-test="checks">
            <thead>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($checks ?? [] as $check) : ?>
                <tr>
                    <td><?= htmlspecialchars($check['id'] ?? '') ?></td>
                    <td><?= htmlspecialchars($check['status_code'] ?? '') ?></td>
                    <td><?= htmlspecialchars($check['h1'] ?? '') ?></td>
                    <td><?= htmlspecialchars($check['title'] ?? '') ?></td>
                    <td><?= htmlspecialchars($check['description'] ?? '') ?></td>
                    <td><?= htmlspecialchars($check['created_at'] ?? '') ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>

<footer class="footer mt-auto py-3 bg-light flex-shrink-0">
    <div class="container text-center">
        <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>